// ===========================
// Mock Data — Merchant Review Dashboard
// ===========================

const MERCHANTS = [
    {
        id: 'MERCH-001',
        name: 'TechFlow Solutions',
        businessType: 'SaaS',
        email: 'admin@techflow.io',
        website: 'https://techflow.io',
        country: 'India',
        registrationNumber: 'CIN-U72200KA2022PTC164832',
        incorporationDate: '2022-03-15',
        annualRevenue: '₹2.4 Cr',
        employees: '15-50',
        directorName: 'Rajesh Kumar',
        directorId: 'AADPK7234R',
        address: '42, 3rd Floor, Koramangala, Bengaluru 560034',
        stage: 'kyb',
        riskTier: 'low',
        assignedTo: { name: 'Priya M.', initials: 'PM' },
        slaHours: 12,
        slaRemaining: 6.7,
        submittedAt: '2026-03-18T08:30:00',
        avatarColor: '#6366f1',
        riskScore: 32,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.2 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'PAN Card - Company', type: 'pdf', size: '0.8 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'GST Registration', type: 'pdf', size: '0.5 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'Director KYC - Aadhaar', type: 'img', size: '2.1 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'Bank Statement (3M)', type: 'pdf', size: '3.4 MB', status: 'pending', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pass', result: 'Clear' },
            { name: 'PEP Check', status: 'pass', result: 'No Match' },
            { name: 'Sanctions List', status: 'pass', result: 'Clear' },
            { name: 'Adverse Media', status: 'pending', result: 'In Progress' },
        ],
        transactions: { volume: '₹12.4L', count: '1,284', chargebackRate: '0.3%' },
        riskSignals: [
            { name: 'Fraud Score', value: '12/100', level: 'low' },
            { name: 'Velocity', value: 'Normal', level: 'low' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: '0.3%', level: 'low' },
        ],
        notes: [
            { author: 'Priya M.', text: 'GST registration matches company PAN. Awaiting bank statement verification.', time: '2h ago', flagged: false },
            { author: 'System', text: 'Auto-populated fields from KYB provider — all company details verified.', time: '4h ago', flagged: false },
        ],
        auditTrail: [
            { type: 'stage', desc: 'Moved to KYB Verification', detail: 'Intake stage completed. All initial documents submitted.', time: '2026-03-18T10:15:00', user: 'Priya M.' },
            { type: 'system', desc: 'Auto-sync: KYB data populated', detail: 'Company registration, PAN, GST details auto-pulled from MCA database.', time: '2026-03-18T10:16:00', user: 'System' },
            { type: 'note', desc: 'Note added', detail: 'GST registration matches company PAN. Awaiting bank statement verification.', time: '2026-03-18T12:30:00', user: 'Priya M.' },
            { type: 'system', desc: 'Document uploaded', detail: 'Bank Statement (3M) uploaded by merchant via portal.', time: '2026-03-18T14:00:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-002',
        name: 'CloudNest AI',
        businessType: 'AI/ML Platform',
        email: 'ops@cloudnest.ai',
        website: 'https://cloudnest.ai',
        country: 'India',
        registrationNumber: 'CIN-U74999DL2023PTC165721',
        incorporationDate: '2023-07-22',
        annualRevenue: '₹85L',
        employees: '5-15',
        directorName: 'Ananya Sharma',
        directorId: 'BWDPS4521K',
        address: '12A, WeWork Embassy, HSR Layout, Bengaluru 560102',
        stage: 'aml',
        riskTier: 'medium',
        assignedTo: { name: 'Arjun S.', initials: 'AS' },
        slaHours: 12,
        slaRemaining: 3.2,
        submittedAt: '2026-03-17T14:00:00',
        avatarColor: '#8b5cf6',
        riskScore: 48,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.1 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'PAN Card - Company', type: 'pdf', size: '0.6 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'Director Passport', type: 'img', size: '3.2 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'Board Resolution', type: 'doc', size: '0.4 MB', status: 'verified', uploadDate: '2026-03-17' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'In Progress' },
            { name: 'PEP Check', status: 'pass', result: 'No Match' },
            { name: 'Sanctions List', status: 'pass', result: 'Clear' },
            { name: 'Adverse Media', status: 'pending', result: 'In Progress' },
        ],
        transactions: { volume: '₹4.2L', count: '312', chargebackRate: '1.2%' },
        riskSignals: [
            { name: 'Fraud Score', value: '38/100', level: 'medium' },
            { name: 'Velocity', value: 'Elevated', level: 'medium' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: '1.2%', level: 'medium' },
        ],
        notes: [
            { author: 'Arjun S.', text: 'Chargeback rate slightly elevated — flagged for deeper review during risk assessment.', time: '5h ago', flagged: true },
        ],
        auditTrail: [
            { type: 'stage', desc: 'Moved to AML/PEP Check', detail: 'KYB verification completed. All documents verified.', time: '2026-03-18T06:00:00', user: 'Arjun S.' },
            { type: 'flag', desc: 'Flag raised: Elevated chargeback rate', detail: 'Chargeback rate at 1.2% — above 1% threshold.', time: '2026-03-18T06:15:00', user: 'Arjun S.' },
            { type: 'system', desc: 'AML screening initiated', detail: 'Automated AML/PEP/Sanctions screening triggered.', time: '2026-03-18T06:20:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-003',
        name: 'PayBridge Corp',
        businessType: 'Fintech',
        email: 'compliance@paybridge.com',
        website: 'https://paybridge.com',
        country: 'Singapore',
        registrationNumber: 'UEN-202312345K',
        incorporationDate: '2023-01-10',
        annualRevenue: 'SGD 1.8M',
        employees: '20-50',
        directorName: 'Michael Chen',
        directorId: 'S8912345A',
        address: '71 Robinson Road, #14-01, Singapore 068895',
        stage: 'intake',
        riskTier: 'unknown',
        assignedTo: { name: 'Riya D.', initials: 'RD' },
        slaHours: 12,
        slaRemaining: 11.5,
        submittedAt: '2026-03-18T21:00:00',
        avatarColor: '#ec4899',
        riskScore: 0,
        documents: [
            { name: 'ACRA Business Profile', type: 'pdf', size: '2.1 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'Director Passport', type: 'img', size: '1.8 MB', status: 'pending', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'Not Started' },
            { name: 'PEP Check', status: 'pending', result: 'Not Started' },
            { name: 'Sanctions List', status: 'pending', result: 'Not Started' },
            { name: 'Adverse Media', status: 'pending', result: 'Not Started' },
        ],
        transactions: { volume: '—', count: '—', chargebackRate: '—' },
        riskSignals: [
            { name: 'Fraud Score', value: 'Pending', level: 'low' },
            { name: 'Velocity', value: 'Pending', level: 'low' },
            { name: 'Geo Risk', value: 'Medium', level: 'medium' },
            { name: 'Chargeback', value: 'N/A', level: 'low' },
        ],
        notes: [],
        auditTrail: [
            { type: 'system', desc: 'Application received', detail: 'PayBridge Corp submitted merchant application via portal.', time: '2026-03-18T21:00:00', user: 'System' },
            { type: 'stage', desc: 'Assigned to Intake', detail: 'Auto-assigned to Riya D. based on workload balancing.', time: '2026-03-18T21:01:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-004',
        name: 'GreenLeaf Organics',
        businessType: 'E-Commerce',
        email: 'info@greenleaforganics.in',
        website: 'https://greenleaforganics.in',
        country: 'India',
        registrationNumber: 'CIN-U15400MH2021PTC163290',
        incorporationDate: '2021-11-03',
        annualRevenue: '₹4.1 Cr',
        employees: '50-100',
        directorName: 'Meera Patel',
        directorId: 'AKLPP8821M',
        address: '305, Trade Tower, BKC, Mumbai 400051',
        stage: 'risk',
        riskTier: 'low',
        assignedTo: { name: 'Vikram T.', initials: 'VT' },
        slaHours: 12,
        slaRemaining: 2.1,
        submittedAt: '2026-03-17T06:00:00',
        avatarColor: '#22c55e',
        riskScore: 18,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.0 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'FSSAI License', type: 'pdf', size: '0.7 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'GST Registration', type: 'pdf', size: '0.4 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'Director KYC - Aadhaar', type: 'img', size: '1.9 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'Bank Statement (3M)', type: 'pdf', size: '4.1 MB', status: 'verified', uploadDate: '2026-03-17' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pass', result: 'Clear' },
            { name: 'PEP Check', status: 'pass', result: 'No Match' },
            { name: 'Sanctions List', status: 'pass', result: 'Clear' },
            { name: 'Adverse Media', status: 'pass', result: 'Clear' },
        ],
        transactions: { volume: '₹38.2L', count: '8,421', chargebackRate: '0.1%' },
        riskSignals: [
            { name: 'Fraud Score', value: '8/100', level: 'low' },
            { name: 'Velocity', value: 'Normal', level: 'low' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: '0.1%', level: 'low' },
        ],
        notes: [
            { author: 'Vikram T.', text: 'All compliance checks passed. Clean profile. Recommending approval.', time: '1h ago', flagged: false },
            { author: 'Priya M.', text: 'KYB and AML stages completed without issues. Forwarded to Risk.', time: '6h ago', flagged: false },
        ],
        auditTrail: [
            { type: 'stage', desc: 'Moved to Risk Review', detail: 'All compliance stages completed. Merchant forwarded to Risk team.', time: '2026-03-18T14:00:00', user: 'System' },
            { type: 'decision', desc: 'Compliance recommendation: Approve', detail: 'All checks passed. No flags or concerns raised during compliance review.', time: '2026-03-18T13:55:00', user: 'Priya M.' },
            { type: 'stage', desc: 'AML/PEP/Sanctions completed', detail: 'All screening checks returned clear results.', time: '2026-03-18T12:00:00', user: 'System' },
            { type: 'note', desc: 'Note added', detail: 'All compliance checks passed. Clean profile. Recommending approval.', time: '2026-03-18T14:30:00', user: 'Vikram T.' },
        ]
    },
    {
        id: 'MERCH-005',
        name: 'QuickLend Finance',
        businessType: 'Lending / NBFC',
        email: 'ops@quicklend.co',
        website: 'https://quicklend.co',
        country: 'India',
        registrationNumber: 'CIN-U65999TN2020PTC137654',
        incorporationDate: '2020-06-18',
        annualRevenue: '₹12 Cr',
        employees: '100-250',
        directorName: 'Suresh Reddy',
        directorId: 'AKRPS6642L',
        address: '18, Anna Salai, Teynampet, Chennai 600018',
        stage: 'kyb',
        riskTier: 'high',
        assignedTo: { name: 'Arjun S.', initials: 'AS' },
        slaHours: 24,
        slaRemaining: 18.3,
        submittedAt: '2026-03-18T04:00:00',
        avatarColor: '#ef4444',
        riskScore: 72,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.3 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'RBI Registration', type: 'pdf', size: '0.9 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'Audited Financials (2Y)', type: 'pdf', size: '8.2 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'Director KYC Bundle', type: 'doc', size: '5.4 MB', status: 'verified', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'Not Started' },
            { name: 'PEP Check', status: 'pending', result: 'Not Started' },
            { name: 'Sanctions List', status: 'pending', result: 'Not Started' },
            { name: 'Adverse Media', status: 'pending', result: 'Not Started' },
        ],
        transactions: { volume: '₹1.2 Cr', count: '14,320', chargebackRate: '2.8%' },
        riskSignals: [
            { name: 'Fraud Score', value: '62/100', level: 'high' },
            { name: 'Velocity', value: 'High', level: 'high' },
            { name: 'Geo Risk', value: 'Medium', level: 'medium' },
            { name: 'Chargeback', value: '2.8%', level: 'high' },
        ],
        notes: [
            { author: 'Arjun S.', text: 'NBFC — requires enhanced due diligence. RBI registration verification pending. High chargeback rate is a concern.', time: '3h ago', flagged: true },
        ],
        auditTrail: [
            { type: 'stage', desc: 'Moved to KYB Verification', detail: 'Intake completed. Flagged as high-risk due to NBFC classification.', time: '2026-03-18T08:00:00', user: 'System' },
            { type: 'flag', desc: 'High-risk classification applied', detail: 'Business type: Lending/NBFC — enhanced due diligence required.', time: '2026-03-18T08:05:00', user: 'System' },
            { type: 'note', desc: 'Analyst note', detail: 'NBFC — requires enhanced due diligence. RBI registration verification pending.', time: '2026-03-18T11:00:00', user: 'Arjun S.' },
        ]
    },
    {
        id: 'MERCH-006',
        name: 'SnapDeal Pro',
        businessType: 'Marketplace',
        email: 'merchant@snapdealpro.com',
        website: 'https://snapdealpro.com',
        country: 'India',
        registrationNumber: 'CIN-U74120HR2024PTC166233',
        incorporationDate: '2024-02-01',
        annualRevenue: '₹35L',
        employees: '5-15',
        directorName: 'Amit Verma',
        directorId: 'DBZPV3341N',
        address: '22, Cyber Hub, Gurugram 122002',
        stage: 'blocked',
        riskTier: 'medium',
        assignedTo: { name: 'Priya M.', initials: 'PM' },
        slaHours: 12,
        slaRemaining: 0,
        submittedAt: '2026-03-16T10:00:00',
        avatarColor: '#f59e0b',
        riskScore: 45,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.0 MB', status: 'verified', uploadDate: '2026-03-16' },
            { name: 'PAN Card - Company', type: 'pdf', size: '0.5 MB', status: 'verified', uploadDate: '2026-03-16' },
            { name: 'Address Proof', type: 'img', size: '1.4 MB', status: 'rejected', uploadDate: '2026-03-16' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pass', result: 'Clear' },
            { name: 'PEP Check', status: 'pass', result: 'No Match' },
            { name: 'Sanctions List', status: 'pass', result: 'Clear' },
            { name: 'Adverse Media', status: 'pass', result: 'Clear' },
        ],
        transactions: { volume: '₹1.8L', count: '145', chargebackRate: '0.8%' },
        riskSignals: [
            { name: 'Fraud Score', value: '28/100', level: 'low' },
            { name: 'Velocity', value: 'Normal', level: 'low' },
            { name: 'Geo Risk', value: 'Medium', level: 'medium' },
            { name: 'Chargeback', value: '0.8%', level: 'low' },
        ],
        notes: [
            { author: 'Priya M.', text: 'Address proof document rejected — image unclear and not matching registered address. Doc request sent.', time: '1d ago', flagged: true },
        ],
        auditTrail: [
            { type: 'system', desc: 'Document request sent', detail: 'Email sent to merchant requesting clearer address proof document.', time: '2026-03-17T09:00:00', user: 'System' },
            { type: 'flag', desc: 'Document rejected', detail: 'Address proof image is unclear and does not match registered address.', time: '2026-03-17T08:45:00', user: 'Priya M.' },
            { type: 'stage', desc: 'Blocked: Awaiting documents', detail: 'Review paused. Merchant needs to re-submit address proof.', time: '2026-03-17T09:00:00', user: 'Priya M.' },
        ]
    },
    {
        id: 'MERCH-007',
        name: 'EduVerse Learning',
        businessType: 'EdTech',
        email: 'admin@eduverse.io',
        website: 'https://eduverse.io',
        country: 'India',
        registrationNumber: 'CIN-U80901KA2022PTC165100',
        incorporationDate: '2022-09-14',
        annualRevenue: '₹1.6 Cr',
        employees: '30-50',
        directorName: 'Kavita Nair',
        directorId: 'ASNPN2287Q',
        address: '8, HSR Layout, Sector 2, Bengaluru 560102',
        stage: 'intake',
        riskTier: 'unknown',
        assignedTo: { name: 'Riya D.', initials: 'RD' },
        slaHours: 12,
        slaRemaining: 10.8,
        submittedAt: '2026-03-18T20:00:00',
        avatarColor: '#3b82f6',
        riskScore: 0,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '0.9 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'PAN Card', type: 'pdf', size: '0.4 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'GST Registration', type: 'pdf', size: '0.5 MB', status: 'pending', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'Not Started' },
            { name: 'PEP Check', status: 'pending', result: 'Not Started' },
            { name: 'Sanctions List', status: 'pending', result: 'Not Started' },
            { name: 'Adverse Media', status: 'pending', result: 'Not Started' },
        ],
        transactions: { volume: '—', count: '—', chargebackRate: '—' },
        riskSignals: [
            { name: 'Fraud Score', value: 'Pending', level: 'low' },
            { name: 'Velocity', value: 'Pending', level: 'low' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: 'N/A', level: 'low' },
        ],
        notes: [],
        auditTrail: [
            { type: 'system', desc: 'Application received', detail: 'EduVerse Learning submitted merchant application.', time: '2026-03-18T20:00:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-008',
        name: 'FitZone Wellness',
        businessType: 'Health & Fitness',
        email: 'biz@fitzone.co.in',
        website: 'https://fitzone.co.in',
        country: 'India',
        registrationNumber: 'CIN-U93000DL2021PTC162999',
        incorporationDate: '2021-04-20',
        annualRevenue: '₹3.2 Cr',
        employees: '25-50',
        directorName: 'Rohan Malhotra',
        directorId: 'BQKPM8812R',
        address: '56, Connaught Place, New Delhi 110001',
        stage: 'kyb',
        riskTier: 'low',
        assignedTo: { name: 'Priya M.', initials: 'PM' },
        slaHours: 12,
        slaRemaining: 8.4,
        submittedAt: '2026-03-18T12:00:00',
        avatarColor: '#14b8a6',
        riskScore: 22,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.1 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'PAN Card - Company', type: 'pdf', size: '0.7 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'FSSAI License', type: 'pdf', size: '0.6 MB', status: 'pending', uploadDate: '2026-03-18' },
            { name: 'Director KYC', type: 'img', size: '2.3 MB', status: 'verified', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'Not Started' },
            { name: 'PEP Check', status: 'pending', result: 'Not Started' },
            { name: 'Sanctions List', status: 'pending', result: 'Not Started' },
            { name: 'Adverse Media', status: 'pending', result: 'Not Started' },
        ],
        transactions: { volume: '₹18.5L', count: '3,210', chargebackRate: '0.2%' },
        riskSignals: [
            { name: 'Fraud Score', value: '14/100', level: 'low' },
            { name: 'Velocity', value: 'Normal', level: 'low' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: '0.2%', level: 'low' },
        ],
        notes: [],
        auditTrail: [
            { type: 'stage', desc: 'Moved to KYB Verification', detail: 'Intake completed. Standard processing.', time: '2026-03-18T14:30:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-009',
        name: 'DataPulse Analytics',
        businessType: 'Data Platform',
        email: 'admin@datapulse.tech',
        website: 'https://datapulse.tech',
        country: 'India',
        registrationNumber: 'CIN-U72300TG2023PTC165890',
        incorporationDate: '2023-05-11',
        annualRevenue: '₹55L',
        employees: '10-25',
        directorName: 'Sneha Iyer',
        directorId: 'AEFPI5523G',
        address: '15, HITEC City, Hyderabad 500081',
        stage: 'intake',
        riskTier: 'unknown',
        assignedTo: { name: 'Vikram T.', initials: 'VT' },
        slaHours: 12,
        slaRemaining: 11.1,
        submittedAt: '2026-03-18T21:30:00',
        avatarColor: '#a855f7',
        riskScore: 0,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.0 MB', status: 'pending', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'Not Started' },
            { name: 'PEP Check', status: 'pending', result: 'Not Started' },
            { name: 'Sanctions List', status: 'pending', result: 'Not Started' },
            { name: 'Adverse Media', status: 'pending', result: 'Not Started' },
        ],
        transactions: { volume: '—', count: '—', chargebackRate: '—' },
        riskSignals: [
            { name: 'Fraud Score', value: 'Pending', level: 'low' },
            { name: 'Velocity', value: 'Pending', level: 'low' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: 'N/A', level: 'low' },
        ],
        notes: [],
        auditTrail: [
            { type: 'system', desc: 'Application received', detail: 'DataPulse Analytics submitted merchant application.', time: '2026-03-18T21:30:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-010',
        name: 'NovaPay International',
        businessType: 'Cross-border Payments',
        email: 'legal@novapay.global',
        website: 'https://novapay.global',
        country: 'UAE',
        registrationNumber: 'DIFC-CL3498',
        incorporationDate: '2022-12-01',
        annualRevenue: 'AED 8.5M',
        employees: '50-100',
        directorName: 'Omar Al-Hassan',
        directorId: 'EID-784-2912-3456789-1',
        address: 'Gate Village 4, DIFC, Dubai, UAE',
        stage: 'aml',
        riskTier: 'medium',
        assignedTo: { name: 'Arjun S.', initials: 'AS' },
        slaHours: 24,
        slaRemaining: 16.5,
        submittedAt: '2026-03-18T02:00:00',
        avatarColor: '#0ea5e9',
        riskScore: 55,
        documents: [
            { name: 'Trade License', type: 'pdf', size: '2.3 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'Shareholder Certificate', type: 'pdf', size: '1.8 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'Director Emirates ID', type: 'img', size: '1.2 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'AML Policy Document', type: 'doc', size: '4.5 MB', status: 'pending', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'In Progress' },
            { name: 'PEP Check', status: 'pass', result: 'No Match' },
            { name: 'Sanctions List', status: 'pending', result: 'In Progress' },
            { name: 'Adverse Media', status: 'pass', result: 'Clear' },
        ],
        transactions: { volume: 'AED 2.1M', count: '5,890', chargebackRate: '0.9%' },
        riskSignals: [
            { name: 'Fraud Score', value: '41/100', level: 'medium' },
            { name: 'Velocity', value: 'Elevated', level: 'medium' },
            { name: 'Geo Risk', value: 'Medium', level: 'medium' },
            { name: 'Chargeback', value: '0.9%', level: 'low' },
        ],
        notes: [
            { author: 'Arjun S.', text: 'Cross-border payments entity — geo risk elevated due to UAE jurisdiction. AML policy document under review.', time: '4h ago', flagged: false },
        ],
        auditTrail: [
            { type: 'stage', desc: 'Moved to AML/PEP Check', detail: 'KYB completed for UAE entity. Enhanced screening initiated.', time: '2026-03-18T10:00:00', user: 'Arjun S.' },
            { type: 'system', desc: 'AML screening initiated', detail: 'Cross-border enhanced AML screening triggered.', time: '2026-03-18T10:05:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-011',
        name: 'UrbanEats Delivery',
        businessType: 'Food Delivery',
        email: 'ops@urbaneats.in',
        website: 'https://urbaneats.in',
        country: 'India',
        registrationNumber: 'CIN-U56000KA2023PTC166100',
        incorporationDate: '2023-08-15',
        annualRevenue: '₹1.1 Cr',
        employees: '15-30',
        directorName: 'Deepika Rao',
        directorId: 'CLRPD7712H',
        address: '99, Indiranagar, Bengaluru 560038',
        stage: 'kyb',
        riskTier: 'low',
        assignedTo: { name: 'Riya D.', initials: 'RD' },
        slaHours: 12,
        slaRemaining: 9.2,
        submittedAt: '2026-03-18T11:00:00',
        avatarColor: '#f97316',
        riskScore: 25,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.0 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'FSSAI License', type: 'pdf', size: '0.8 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'PAN Card', type: 'pdf', size: '0.3 MB', status: 'verified', uploadDate: '2026-03-18' },
            { name: 'Director Aadhaar', type: 'img', size: '1.5 MB', status: 'pending', uploadDate: '2026-03-18' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pending', result: 'Not Started' },
            { name: 'PEP Check', status: 'pending', result: 'Not Started' },
            { name: 'Sanctions List', status: 'pending', result: 'Not Started' },
            { name: 'Adverse Media', status: 'pending', result: 'Not Started' },
        ],
        transactions: { volume: '₹8.3L', count: '2,100', chargebackRate: '0.4%' },
        riskSignals: [
            { name: 'Fraud Score', value: '15/100', level: 'low' },
            { name: 'Velocity', value: 'Normal', level: 'low' },
            { name: 'Geo Risk', value: 'Low', level: 'low' },
            { name: 'Chargeback', value: '0.4%', level: 'low' },
        ],
        notes: [],
        auditTrail: [
            { type: 'stage', desc: 'Moved to KYB Verification', detail: 'Intake completed. Documents submitted.', time: '2026-03-18T13:00:00', user: 'System' },
        ]
    },
    {
        id: 'MERCH-012',
        name: 'CryptoVault Exchange',
        businessType: 'Crypto Exchange',
        email: 'compliance@cryptovault.exchange',
        website: 'https://cryptovault.exchange',
        country: 'India',
        registrationNumber: 'CIN-U65100KA2024PTC167500',
        incorporationDate: '2024-01-15',
        annualRevenue: '₹22 Cr',
        employees: '25-50',
        directorName: 'Karthik Bhat',
        directorId: 'AGHPB1123K',
        address: '401, Prestige Tech Park, Whitefield, Bengaluru 560066',
        stage: 'risk',
        riskTier: 'high',
        assignedTo: { name: 'Vikram T.', initials: 'VT' },
        slaHours: 24,
        slaRemaining: 14.7,
        submittedAt: '2026-03-17T18:00:00',
        avatarColor: '#dc2626',
        riskScore: 78,
        documents: [
            { name: 'Certificate of Incorporation', type: 'pdf', size: '1.2 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'FIU Registration', type: 'pdf', size: '0.9 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'AML/CFT Policy', type: 'doc', size: '6.2 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'Director KYC Bundle', type: 'doc', size: '4.8 MB', status: 'verified', uploadDate: '2026-03-17' },
            { name: 'Audited Financials', type: 'pdf', size: '7.1 MB', status: 'verified', uploadDate: '2026-03-17' },
        ],
        checks: [
            { name: 'AML Screening', status: 'pass', result: 'Clear' },
            { name: 'PEP Check', status: 'fail', result: 'Match Found' },
            { name: 'Sanctions List', status: 'pass', result: 'Clear' },
            { name: 'Adverse Media', status: 'fail', result: '2 Hits' },
        ],
        transactions: { volume: '₹8.4 Cr', count: '45,200', chargebackRate: '1.8%' },
        riskSignals: [
            { name: 'Fraud Score', value: '68/100', level: 'high' },
            { name: 'Velocity', value: 'Very High', level: 'high' },
            { name: 'Geo Risk', value: 'Medium', level: 'medium' },
            { name: 'Chargeback', value: '1.8%', level: 'high' },
        ],
        notes: [
            { author: 'Vikram T.', text: 'PEP match found for director — political connections flagged. Adverse media hits related to crypto regulation concerns. Requires senior review before decision.', time: '2h ago', flagged: true },
            { author: 'Arjun S.', text: 'Crypto exchange — high inherent risk category. Enhanced due diligence completed at AML stage.', time: '8h ago', flagged: true },
        ],
        auditTrail: [
            { type: 'stage', desc: 'Moved to Risk Review', detail: 'Compliance stages completed with flags — forwarded to Risk for final assessment.', time: '2026-03-18T10:00:00', user: 'System' },
            { type: 'flag', desc: 'PEP match detected', detail: 'Director Karthik Bhat — potential political exposure flagged by screening system.', time: '2026-03-18T04:00:00', user: 'System' },
            { type: 'flag', desc: 'Adverse media hits', detail: '2 adverse media results related to regulatory scrutiny of crypto operations.', time: '2026-03-18T04:05:00', user: 'System' },
            { type: 'note', desc: 'Analyst note', detail: 'PEP match found. Adverse media hits. Requires senior review.', time: '2026-03-18T12:00:00', user: 'Vikram T.' },
        ]
    }
];

// Detailed risk signal data per merchant — uses real payment-industry variable names
// Attached to each merchant via ID lookup
const RISK_SIGNALS_DETAILED = {
    'MERCH-001': {
        fraudScore: {
            composite: 12,
            mlModelScore: 9,       // ML ensemble output (0-100)
            ruleEngineScore: 15,    // Rule-based heuristic score
            modelVersion: 'v3.4.1',
            lastUpdated: '2026-03-18T14:22:00',
        },
        velocity: {
            txnPerDay_avg: 14.2,
            txnPerDay_p95: 28,
            avgTicketSize: '₹965',
            maxTicketSize: '₹18,400',
            peakHourConcentration: 0.18,   // % of daily txn in single hour
            categoryAvg_txnPerDay: 22,
            velocityRatio: 0.65,            // merchant vs category avg
            spikeDetected: false,
            refundRate: 0.02,               // 2%
        },
        geoRisk: {
            registrationCountry: 'IN',
            countryRiskRating: 'Low',       // FATF rating
            ipGeolocationMatch: 98.1,       // % of txns matching declared country
            multiGeoActivity: false,
            highRiskJurisdictionExposure: 0, // % txns from FATF grey/blacklist
            vpnProxyDetectionRate: 0.4,     // %
            sanctionedCountryExposure: 0,
        },
        chargeback: {
            currentRate: 0.003,   // 0.3%
            rate_30d: 0.003,
            rate_90d: 0.002,
            trend: 'stable',      // stable | increasing | decreasing
            totalDisputes_90d: 4,
            wonRate: 0.75,        // % disputes won
            topReasonCode: 'Product Not Received',
            visaTC40Count: 0,
            mastercardSAFECount: 0,
            thresholdStatus: 'normal',  // normal | warning | breach
        },
        deviceBehavioral: {
            uniqueDevices_30d: 842,
            avgSessionDuration: '4m 12s',
            mobileVsDesktop: '62% / 38%',
            deviceFingerprintCollisionRate: 0.1,  // %
            botTrafficRate: 0.3,                   // %
            '3dsAdoptionRate': 0.94,               // 94%
            cardTestingIndicator: false,
        },
        businessProfile: {
            mcc: '5734',                    // Computer Software Stores
            mccDescription: 'SaaS / Software',
            mccRiskCategory: 'Low',
            businessAge_months: 48,
            monthlyVolumeGrowth: 0.08,      // 8% MoM
            avgTxnAmount: '₹965',
            declaredVsActualRevenue: 0.96,  // 96% match
            websiteStatus: 'Active',
            sslCertValid: true,
            domainAge_months: 50,
        },
    },
    'MERCH-002': {
        fraudScore: {
            composite: 38,
            mlModelScore: 34,
            ruleEngineScore: 42,
            modelVersion: 'v3.4.1',
            lastUpdated: '2026-03-18T06:10:00',
        },
        velocity: {
            txnPerDay_avg: 8.7,
            txnPerDay_p95: 22,
            avgTicketSize: '₹1,346',
            maxTicketSize: '₹42,000',
            peakHourConcentration: 0.31,
            categoryAvg_txnPerDay: 12,
            velocityRatio: 0.73,
            spikeDetected: true,
            refundRate: 0.06,
        },
        geoRisk: {
            registrationCountry: 'IN',
            countryRiskRating: 'Low',
            ipGeolocationMatch: 91.3,
            multiGeoActivity: true,
            highRiskJurisdictionExposure: 2.1,
            vpnProxyDetectionRate: 3.8,
            sanctionedCountryExposure: 0,
        },
        chargeback: {
            currentRate: 0.012,
            rate_30d: 0.012,
            rate_90d: 0.008,
            trend: 'increasing',
            totalDisputes_90d: 9,
            wonRate: 0.44,
            topReasonCode: 'Unauthorized Transaction',
            visaTC40Count: 2,
            mastercardSAFECount: 1,
            thresholdStatus: 'warning',
        },
        deviceBehavioral: {
            uniqueDevices_30d: 210,
            avgSessionDuration: '2m 48s',
            mobileVsDesktop: '71% / 29%',
            deviceFingerprintCollisionRate: 1.4,
            botTrafficRate: 2.1,
            '3dsAdoptionRate': 0.78,
            cardTestingIndicator: false,
        },
        businessProfile: {
            mcc: '7372',
            mccDescription: 'Computer Programming / Data Processing',
            mccRiskCategory: 'Medium',
            businessAge_months: 32,
            monthlyVolumeGrowth: 0.22,
            avgTxnAmount: '₹1,346',
            declaredVsActualRevenue: 0.82,
            websiteStatus: 'Active',
            sslCertValid: true,
            domainAge_months: 30,
        },
    },
    'MERCH-004': {
        fraudScore: {
            composite: 8,
            mlModelScore: 5,
            ruleEngineScore: 11,
            modelVersion: 'v3.4.1',
            lastUpdated: '2026-03-18T13:50:00',
        },
        velocity: {
            txnPerDay_avg: 280,
            txnPerDay_p95: 420,
            avgTicketSize: '₹454',
            maxTicketSize: '₹8,200',
            peakHourConcentration: 0.14,
            categoryAvg_txnPerDay: 310,
            velocityRatio: 0.90,
            spikeDetected: false,
            refundRate: 0.03,
        },
        geoRisk: {
            registrationCountry: 'IN',
            countryRiskRating: 'Low',
            ipGeolocationMatch: 99.4,
            multiGeoActivity: false,
            highRiskJurisdictionExposure: 0,
            vpnProxyDetectionRate: 0.2,
            sanctionedCountryExposure: 0,
        },
        chargeback: {
            currentRate: 0.001,
            rate_30d: 0.001,
            rate_90d: 0.001,
            trend: 'stable',
            totalDisputes_90d: 8,
            wonRate: 0.88,
            topReasonCode: 'Merchandise Not Received',
            visaTC40Count: 0,
            mastercardSAFECount: 0,
            thresholdStatus: 'normal',
        },
        deviceBehavioral: {
            uniqueDevices_30d: 5120,
            avgSessionDuration: '6m 34s',
            mobileVsDesktop: '78% / 22%',
            deviceFingerprintCollisionRate: 0.05,
            botTrafficRate: 0.1,
            '3dsAdoptionRate': 0.97,
            cardTestingIndicator: false,
        },
        businessProfile: {
            mcc: '5411',
            mccDescription: 'Grocery / Organic Retail',
            mccRiskCategory: 'Low',
            businessAge_months: 52,
            monthlyVolumeGrowth: 0.05,
            avgTxnAmount: '₹454',
            declaredVsActualRevenue: 0.98,
            websiteStatus: 'Active',
            sslCertValid: true,
            domainAge_months: 54,
        },
    },
    'MERCH-005': {
        fraudScore: {
            composite: 62,
            mlModelScore: 58,
            ruleEngineScore: 66,
            modelVersion: 'v3.4.1',
            lastUpdated: '2026-03-18T10:45:00',
        },
        velocity: {
            txnPerDay_avg: 477,
            txnPerDay_p95: 890,
            avgTicketSize: '₹8,380',
            maxTicketSize: '₹2,50,000',
            peakHourConcentration: 0.42,
            categoryAvg_txnPerDay: 210,
            velocityRatio: 2.27,
            spikeDetected: true,
            refundRate: 0.09,
        },
        geoRisk: {
            registrationCountry: 'IN',
            countryRiskRating: 'Low',
            ipGeolocationMatch: 86.2,
            multiGeoActivity: true,
            highRiskJurisdictionExposure: 4.8,
            vpnProxyDetectionRate: 6.1,
            sanctionedCountryExposure: 0.3,
        },
        chargeback: {
            currentRate: 0.028,
            rate_30d: 0.028,
            rate_90d: 0.019,
            trend: 'increasing',
            totalDisputes_90d: 401,
            wonRate: 0.31,
            topReasonCode: 'Fraudulent Transaction',
            visaTC40Count: 12,
            mastercardSAFECount: 8,
            thresholdStatus: 'breach',
        },
        deviceBehavioral: {
            uniqueDevices_30d: 9800,
            avgSessionDuration: '1m 42s',
            mobileVsDesktop: '55% / 45%',
            deviceFingerprintCollisionRate: 4.2,
            botTrafficRate: 7.8,
            '3dsAdoptionRate': 0.61,
            cardTestingIndicator: true,
        },
        businessProfile: {
            mcc: '6012',
            mccDescription: 'Financial Institutions / NBFC',
            mccRiskCategory: 'High',
            businessAge_months: 69,
            monthlyVolumeGrowth: 0.31,
            avgTxnAmount: '₹8,380',
            declaredVsActualRevenue: 0.74,
            websiteStatus: 'Active',
            sslCertValid: true,
            domainAge_months: 72,
        },
    },
    'MERCH-010': {
        fraudScore: {
            composite: 41,
            mlModelScore: 38,
            ruleEngineScore: 44,
            modelVersion: 'v3.4.1',
            lastUpdated: '2026-03-18T10:02:00',
        },
        velocity: {
            txnPerDay_avg: 196,
            txnPerDay_p95: 380,
            avgTicketSize: 'AED 356',
            maxTicketSize: 'AED 45,000',
            peakHourConcentration: 0.26,
            categoryAvg_txnPerDay: 150,
            velocityRatio: 1.31,
            spikeDetected: false,
            refundRate: 0.04,
        },
        geoRisk: {
            registrationCountry: 'AE',
            countryRiskRating: 'Medium',
            ipGeolocationMatch: 72.4,
            multiGeoActivity: true,
            highRiskJurisdictionExposure: 8.3,
            vpnProxyDetectionRate: 5.2,
            sanctionedCountryExposure: 1.1,
        },
        chargeback: {
            currentRate: 0.009,
            rate_30d: 0.009,
            rate_90d: 0.007,
            trend: 'stable',
            totalDisputes_90d: 53,
            wonRate: 0.58,
            topReasonCode: 'Services Not Rendered',
            visaTC40Count: 3,
            mastercardSAFECount: 2,
            thresholdStatus: 'normal',
        },
        deviceBehavioral: {
            uniqueDevices_30d: 3400,
            avgSessionDuration: '3m 08s',
            mobileVsDesktop: '48% / 52%',
            deviceFingerprintCollisionRate: 2.1,
            botTrafficRate: 1.4,
            '3dsAdoptionRate': 0.82,
            cardTestingIndicator: false,
        },
        businessProfile: {
            mcc: '4829',
            mccDescription: 'Money Transfer / Cross-border Payments',
            mccRiskCategory: 'High',
            businessAge_months: 39,
            monthlyVolumeGrowth: 0.14,
            avgTxnAmount: 'AED 356',
            declaredVsActualRevenue: 0.88,
            websiteStatus: 'Active',
            sslCertValid: true,
            domainAge_months: 38,
        },
    },
    'MERCH-012': {
        fraudScore: {
            composite: 68,
            mlModelScore: 72,
            ruleEngineScore: 64,
            modelVersion: 'v3.4.1',
            lastUpdated: '2026-03-18T09:30:00',
        },
        velocity: {
            txnPerDay_avg: 1507,
            txnPerDay_p95: 3200,
            avgTicketSize: '₹18,580',
            maxTicketSize: '₹12,00,000',
            peakHourConcentration: 0.38,
            categoryAvg_txnPerDay: 480,
            velocityRatio: 3.14,
            spikeDetected: true,
            refundRate: 0.11,
        },
        geoRisk: {
            registrationCountry: 'IN',
            countryRiskRating: 'Low',
            ipGeolocationMatch: 68.7,
            multiGeoActivity: true,
            highRiskJurisdictionExposure: 12.4,
            vpnProxyDetectionRate: 14.8,
            sanctionedCountryExposure: 2.3,
        },
        chargeback: {
            currentRate: 0.018,
            rate_30d: 0.018,
            rate_90d: 0.014,
            trend: 'increasing',
            totalDisputes_90d: 814,
            wonRate: 0.22,
            topReasonCode: 'Fraudulent Transaction',
            visaTC40Count: 28,
            mastercardSAFECount: 19,
            thresholdStatus: 'breach',
        },
        deviceBehavioral: {
            uniqueDevices_30d: 18400,
            avgSessionDuration: '1m 18s',
            mobileVsDesktop: '44% / 56%',
            deviceFingerprintCollisionRate: 8.6,
            botTrafficRate: 12.3,
            '3dsAdoptionRate': 0.52,
            cardTestingIndicator: true,
        },
        businessProfile: {
            mcc: '6051',
            mccDescription: 'Cryptocurrency / Digital Asset Exchange',
            mccRiskCategory: 'Critical',
            businessAge_months: 26,
            monthlyVolumeGrowth: 0.42,
            avgTxnAmount: '₹18,580',
            declaredVsActualRevenue: 0.61,
            websiteStatus: 'Active',
            sslCertValid: true,
            domainAge_months: 24,
        },
    },
};

// Helper: get detailed risk for a merchant (falls back to a generated default)
function getRiskDetails(merchantId) {
    if (RISK_SIGNALS_DETAILED[merchantId]) return RISK_SIGNALS_DETAILED[merchantId];
    // Generate a lightweight default for merchants without explicit data
    const m = MERCHANTS.find(x => x.id === merchantId);
    const score = m ? m.riskScore : 0;
    return {
        fraudScore: { composite: score, mlModelScore: Math.round(score * 0.85), ruleEngineScore: Math.round(score * 1.1), modelVersion: 'v3.4.1', lastUpdated: new Date().toISOString() },
        velocity: { txnPerDay_avg: '—', txnPerDay_p95: '—', avgTicketSize: '—', maxTicketSize: '—', peakHourConcentration: 0, categoryAvg_txnPerDay: '—', velocityRatio: 0, spikeDetected: false, refundRate: 0 },
        geoRisk: { registrationCountry: m ? m.country.substring(0,2).toUpperCase() : '—', countryRiskRating: 'Pending', ipGeolocationMatch: 0, multiGeoActivity: false, highRiskJurisdictionExposure: 0, vpnProxyDetectionRate: 0, sanctionedCountryExposure: 0 },
        chargeback: { currentRate: 0, rate_30d: 0, rate_90d: 0, trend: '—', totalDisputes_90d: 0, wonRate: 0, topReasonCode: '—', visaTC40Count: 0, mastercardSAFECount: 0, thresholdStatus: 'normal' },
        deviceBehavioral: { uniqueDevices_30d: 0, avgSessionDuration: '—', mobileVsDesktop: '—', deviceFingerprintCollisionRate: 0, botTrafficRate: 0, '3dsAdoptionRate': 0, cardTestingIndicator: false },
        businessProfile: { mcc: '—', mccDescription: 'Pending Classification', mccRiskCategory: 'Pending', businessAge_months: 0, monthlyVolumeGrowth: 0, avgTxnAmount: '—', declaredVsActualRevenue: 0, websiteStatus: 'Pending', sslCertValid: false, domainAge_months: 0 },
    };
}

// Analytics data
const ANALYTICS = {
    tatTrend: [
        { day: 'Mar 1', value: 42 },
        { day: 'Mar 3', value: 38 },
        { day: 'Mar 5', value: 36 },
        { day: 'Mar 7', value: 32 },
        { day: 'Mar 9', value: 28 },
        { day: 'Mar 11', value: 30 },
        { day: 'Mar 13', value: 24 },
        { day: 'Mar 15', value: 22 },
        { day: 'Mar 17', value: 20 },
        { day: 'Mar 18', value: 18.4 },
    ],
    bottlenecks: [
        { name: 'Intake', avgHours: 2.1, percentage: 12, color: '#3b82f6' },
        { name: 'KYB Verification', avgHours: 6.8, percentage: 38, color: '#8b5cf6' },
        { name: 'AML / PEP / Sanctions', avgHours: 5.2, percentage: 29, color: '#f59e0b' },
        { name: 'Risk Review', avgHours: 3.8, percentage: 21, color: '#ec4899' },
    ],
    volume: [
        { label: 'Reviewed This Week', count: 28 },
        { label: 'Approved', count: 22 },
        { label: 'Rejected', count: 3 },
        { label: 'Escalated', count: 2 },
        { label: 'Blocked', count: 1 },
    ]
};
